version: '3'
services:
  container:
    image: ggolub/cloud-tools
    container_name: cloud-tools
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/local
    environment:
      DISPLAY: host.docker.internal:0.0
